version: '3.3'
services:
    bldr:
        build:
            context: .
            args:
                - uservdi
                - user
                - group
                - uid
                - gid
        environment:
            USER: ${uservdi}
        env_file:
            - armcc.env
        volumes:
            - type: volume
              source: ssh
              target: /home/${user}/.ssh
              read_only: true
            - type: volume
              source: build_tools
              target: /mnt/build_tools
              read_only: true
            - type: volume
              source: git
              target: /home/${user}/git
            - ~/sign.txt:/sign.txt
        hostname: bldr
        working_dir: /home/${user}/git
        user: ${user}
        privileged: true
        tty: true
        stdin_open: true
        ports:
          - "5000:5000"
volumes:
    ssh:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,ro,nolock,hard,nointr,nfsvers=3
            device: :${volume_root}/${user}/.ssh
    build_tools:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,ro,nolock,hard,nointr,nfsvers=3
            device: :${volume_root}/${user}/build_tools
    git:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: :${volume_git}
