version: '3.3'
services:
    bldr:
        build:
            context: .
            args:
                - uservdi
                - user
                - group
                - uid
                - gid
        environment:
            USER: ${uservdi}
        env_file:
            - armcc.env
        volumes:
            - type: volume
              source: ssh
              target: /home/${user}/.ssh
            - type: volume
              source: build_tools
              target: /mnt/build_tools
            - type: volume
              source: git
              target: /home/${user}/git
            - type: volume
              source: defects
              target: /home/${user}/defects
            - ~/sign.txt:/sign.txt
        hostname: bldr
        working_dir: /home/${user}/git
        user: ${user}
        privileged: true
        tty: true
        stdin_open: true
        ports:
          - "5000:5000"

volumes:
    ssh:
        driver: local
        driver_opts:
            #type: none
            #o: bind
            #device: /Users/${user}/.ssh
            type: nfs
            o: addr=host.docker.internal,ro,nolock,hard,nointr,nfsvers=3,wsize=131072,rsize=131072
              #o: addr=host.docker.internal,ro,nolock,hard,nointr,nfsvers=3
            device: :${volume_root}/${user}/.ssh
    build_tools:
        driver: local
        driver_opts:
            #type: none
            #o: bind
            #device: /Users/${user}/build_tools
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,wsize=131072,rsize=131072
              #o: addr=host.docker.internal,ro,nolock,hard,nointr,nfsvers=3
            #o: addr=host.docker.internal,ro,nolock,hard,nointr,nfsvers=3,wsize=1048576,rsize=1048576
            device: :${volume_root}/${user}/build_tools
    git:
        driver: local
        driver_opts:
            #type: none
            #o: bind
            #device: /Users/${user}/git
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,wsize=131072,rsize=131072
            #o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: :${volume_git}
    defects:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,wsize=131072,rsize=131072
            device: :${volume_root}/${user}/defects
