#!/bin/bash

# This script is called by the run script. It is not intended to be called directly. To rebuild the
# container, use 'run --rebuild' with appropriate options.

usage="This script is called by the run script. It is not intended to be called directly. To rebuild the
container, use 'run --rebuild' with appropriate options."

while (( "$#" )); do
   case "$1" in
     -h|--help)
       echo -e $usage
       exit 0
       ;;
     *) # unsupported option
       echo -e $usage
       echo "Error: Unsupported flag $1" >&2
       exit 1
       ;;
   esac
done

#
# Check the environment and make sure all variables are defined
#
required_env=( user group uid gid volume_root armds_tgz armds_dir armds_installer armds_installdir)
for e in ${required_env[@]}; do
    if [ -z ${!e} ]; then
        echo "ERROR: Requires environment variable '$e'. Only run this script with 'run --rebuild'."
        exit 1
    fi
done

#
# The container mounts these directories, so make sure they exist
#
git_dir="$HOME/git"
if [ ! -d $git_dir ]; then
    echo "Creating directory $git_dir..."
    mkdir $git_dir || exit 1
fi
ssh_dir="$HOME/.ssh"
if [ ! -d $ssh_dir ]; then
    echo "Creating directory $ssh_dir..."
    mkdir $ssh_dir || exit 1
fi

#
# There are compiler and coverity tools needed by the container.  These tools will be installed on the
# host and the volume will be NFS mounted to the container.
#
build_tools="$HOME/build_tools"
if [ ! -d $build_tools ]; then
    echo "Creating directory $build_tools..."
    mkdir $build_tools || exit 1
fi

#
# Copy files needed to build container from home directory
# All of these files are optional and will only be copied to the container if they exist.
#
files_to_copy=( \
    ~/.vimrc \
    ~/.bashrc \
    ~/.gitconfig \
    ~/.gitignore \
    "$build_tools/$armds_tgz" \ 
)
for file in ${files_to_copy[@]}; do
    if [ -e $file ] && [ ! -e "./$(basename $file)" ]; then
        cp $file .
    fi
done

#
# Finally build the container using the docker-compose.yml file
#
docker-compose --verbose build armds
